config_version = 14

[backdrop]
enabled = true

[bar]
order = [ "Status" ]

    [bar.Status]
    background_opacity = 0.79999998211860657
    capsule_group = []
    concave_edge_corners = false
    end = [
        "cpu",
        "ram",
        "temp",
        "spacer_2",
        "network",
        "network_tx",
        "network_rx",
        "spacer_3",
        "volume",
        "brightness",
        "battery",
        "spacer_4",
        "tray",
        "notifications",
        "session"
    ]
    font_family = "FiraCode Nerd Font Propo Ret"
    font_weight = 400
    margin_ends = 0
    radius = 0
    scale = 0.95000000670552254
    start = [ "wallhaven_2", "workspaces" ]
    thickness = 30

        [bar.Status.monitor.DP-3]
        center = []
        position = "top"
        start = [ "workspaces", "media" ]

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
background_opacity = 0.79999998211860657
enabled = true
reserve_space = false

[idle]
behavior_order = [ "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 5

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 600.0

[lockscreen]
allow_empty_password = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@DP-3" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1440.0003662109375
    cy = 1438.0001220703125
    output = "DP-1"
    placement_height = 1620.0
    placement_width = 2880.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 810.0
    cx = 720.0
    cy = 2378.0
    output = "DP-3"
    placement_height = 2560.0
    placement_width = 1440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[osd.kinds]
keyboard_layout = false

[plugins]
enabled = [ "felipeartur/ai-usagebar", "noctalia/screen_recorder", "noctalia/wallhaven", "oldirtty/color_picker" ]

[shell]
avatar_path = "/home/nvirellia/Downloads/ChatGPT Image Sep 20, 2026, 11_58_53 PM.png"
corner_radius_scale = 0.7500000111758709
lang = "zh-Hans"
niri_overview_type_to_launch_enabled = true
polkit_agent = true

    [shell.launcher]
    app_grid = true
    fetch_exchange_rates = false

    [shell.panel]
    open_near_click_control_center = true
    open_near_click_session = true

    [shell.screenshot]
    annotate = true

[theme]
builtin = "Nord"
mode = "dark"
shell_mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

[wallpaper.default]
path = "/home/nvirellia/Pictures/wallhaven-d8vv8j.jpg"

[wallpaper.last]
path = "/home/nvirellia/Pictures/wallhaven-d8vv8j.jpg"

[wallpaper.monitors.DP-1]
path = "/home/nvirellia/Pictures/wallhaven-d8vv8j.jpg"

[wallpaper.monitors.DP-3]
path = "/home/nvirellia/Pictures/wallhaven-d8vv8j.jpg"

[widget.bar]
capsule = true
capsule_padding = 12
type = "felipeartur/ai-usagebar:bar"
vendor = "openai"

[widget.brightness]
capsule = true

[widget.launcher]
glyph = "noctalia"

[widget.media]
hide_when_no_media = true
show_progress = true

[widget.network]
show_label = false

[widget.spacer_2]
type = "spacer"

[widget.spacer_3]
type = "spacer"

[widget.spacer_4]
type = "spacer"

[widget.sysmon]
stat = "swap_pct"

[widget.taskbar]
focused_output_only = true
group_by_workspace = true
show_all_outputs = true

[widget.volume]
capsule = false
capsule_padding = 12

[widget.wallhaven_2]
type = "noctalia/wallhaven:wallhaven"